set AUTHOR=%1
set AUTHOR=%AUTHOR:"=%
set EMAIL=%2
set EMAIL=%EMAIL:"=%
set GIT_COMMITTER_DATE=%3
set GIT_COMMITTER_DATE=%GIT_COMMITTER_DATE:"=%.000000000 +0300
set GIT_COMMITTER_NAME=%AUTHOR%
set GIT_COMMITTER_EMAIL=%EMAIL%
set MESSAGE=%4
set MESSAGE=%MESSAGE:"=%

git commit --date="%GIT_COMMITTER_DATE%" --author="%AUTHOR% <%EMAIL%>" -m "%MESSAGE%"
